days=("sun",["mon"],"True",(1,2,3))
print(len(days))
print(days[0][2])
print(days[3][2])
print(f"display the all values is:{len(days[3])}")
print(f"{len(days[3])}")
add=days+(8,9)
print(add)
op=add+(11,3)
print(op)